*In Numpy we'll find:*
- ndarray, an efficient multidimentional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities
- Mathematical functions for fast operations on entire arrays of data without having to write loops
- Tools for reading/writing array data to disk and working with memory-mapped files
- Linear Algebra, random number generation, and Fourier transform capabilities
- A C API for connecting Numpy with libraries written in C, C++, or Fortran 

In [2]:
import numpy as np
import sys

# Python list
py_list = [1, 2, 3, 4, 5, 6]
print(f"Python list size: {sys.getsizeof(py_list)} bytes")  # Memory used by the list object
print(f"Memory per element (Python list): {sys.getsizeof(py_list[0])} bytes")  # Memory per element

# NumPy array
np_array = np.array([1, 2, 3, 4, 5])
print(f"NumPy array size: {np_array.nbytes} bytes")  # Total memory used by the array


Python list size: 104 bytes
Memory per element (Python list): 28 bytes
NumPy array size: 40 bytes


### The numpy ndarray

In [3]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
#scalar multiplication 
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
#vectorized addition
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [9]:
# every array has a "shape", which is a tuple indicating the size of each dimention
data.shape

(2, 3)

In [11]:
# numpy arrays are homegenous (of the same type) -> "dtype" helps us chech that type
data.dtype

dtype('float64')

In [12]:
# creating ndarray
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
# nested sequences, like a list of equal-length lists, will be converted into a multidimensional array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# naturally, since we have created numpy object from a list of lists, our array will have two dimentions.
# Let's check that with "ndim"
print(f"Number of dimentions in our array: {arr2.ndim}")
print(f"Tuple portraying shape of our array:  {arr2.shape}")

Number of dimentions in our array: 2
Tuple portraying shape of our array:  (2, 4)


Unless explicitly specified, numpy.array tries to infer a good data type for the array that it creates. The data type is stored in a special dtype metadata object.

In [18]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [19]:
# in addition to numpy.array there are other functions for creating new arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
?np.empty
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

It’s not safe to assume that numpy.empty will return an array of all zeros. This function returns uninitialized memory and thus may contain nonzero "garbage" values. You should use this function only if you intend to populate the new array with data.

In [26]:
# numpy.arange is an array-valued version of the python range function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])